// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function ConnectToWifi(arg1:string,arg2:string):Promise<void>;

export function DefrostSettingsUpdate(arg1:string):Promise<void>;

export function FetchHistoryRaw(arg1:string,arg2:string):Promise<Array<number>>;

export function GetDefrostSettings():Promise<string>;

export function GetHistoryData(arg1:string):Promise<Array<backend.HistoryEntry>>;

export function GetTemperature():Promise<number>;

export function ListWifiSSIDs():Promise<Array<string>>;
