// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function FetchHistoryRaw(arg1:string,arg2:string):Promise<Array<number>>;

export function GetHistoryData(arg1:string):Promise<Array<backend.HistoryEntry>>;

export function GetTemperature():Promise<number>;
