// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToWifi(arg1, arg2) {
  return window['go']['backend']['App']['ConnectToWifi'](arg1, arg2);
}

export function DefrostSettingsUpdate(arg1) {
  return window['go']['backend']['App']['DefrostSettingsUpdate'](arg1);
}

export function FetchHistoryRaw(arg1, arg2) {
  return window['go']['backend']['App']['FetchHistoryRaw'](arg1, arg2);
}

export function GetDefrostSettings() {
  return window['go']['backend']['App']['GetDefrostSettings']();
}

export function GetDeviceNetworkInfo() {
  return window['go']['backend']['App']['GetDeviceNetworkInfo']();
}

export function GetHistoryData(arg1) {
  return window['go']['backend']['App']['GetHistoryData'](arg1);
}

export function GetTemperature() {
  return window['go']['backend']['App']['GetTemperature']();
}

export function ListWifiSSIDs() {
  return window['go']['backend']['App']['ListWifiSSIDs']();
}

export function SendCANFrame(arg1, arg2, arg3) {
  return window['go']['backend']['App']['SendCANFrame'](arg1, arg2, arg3);
}

export function Shutdown(arg1) {
  return window['go']['backend']['App']['Shutdown'](arg1);
}

export function StopCAN() {
  return window['go']['backend']['App']['StopCAN']();
}
