// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchHistoryRaw(arg1, arg2) {
  return window['go']['backend']['App']['FetchHistoryRaw'](arg1, arg2);
}

export function GetHistoryData(arg1) {
  return window['go']['backend']['App']['GetHistoryData'](arg1);
}

export function GetTemperature() {
  return window['go']['backend']['App']['GetTemperature']();
}
